#!/usr/bin/env python3
"""Convert a launch reference trajectory (.npz) into MJPC keyframes.

Usage:
  npz_to_keyframes.py [src.npz] [dst.xml]

Defaults: reference/launch.npz -> launch_reference.xml (next to this script).

The npz must contain:
  time (N,), qpos (N, 19), qvel (N, 18), joint_names (12,),
  hands_contact (N,), feet_contact (N,)

Output (included from task.xml):
  - keyframes launch_ref_000 ... launch_ref_{N-1} with time, qpos, qvel
  - custom numerics launch_ref_hands_contact, launch_ref_feet_contact (N each)
  - custom numeric launch_ref_takeoff: first time with no hand or foot contact
"""
import os
import sys

import numpy as np

# hinge order in pterosaur_torque.xml (qpos[7:])
MODEL_JOINTS = [
    'leftarm_shoulder1', 'leftarm_shoulder2', 'leftarm_elbow',
    'rightarm_shoulder1', 'rightarm_shoulder2', 'rightarm_elbow',
    'leftleg_hip1', 'leftleg_hip2', 'leftleg_knee',
    'rightleg_hip1', 'rightleg_hip2', 'rightleg_knee',
]

here = os.path.dirname(os.path.abspath(__file__))
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    here, 'reference', 'launch.npz')
dst = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
    here, 'launch_reference.xml')

d = np.load(src)
time = d['time']
qpos = d['qpos']
qvel = d['qvel']
hands = d['hands_contact'].astype(bool)
feet = d['feet_contact'].astype(bool)
n = len(time)

names = [str(s) for s in d['joint_names']]
if names != MODEL_JOINTS:
  sys.exit(f'joint order mismatch:\n  npz:   {names}\n  model: {MODEL_JOINTS}')
if qpos.shape != (n, 19) or qvel.shape != (n, 18):
  sys.exit(f'unexpected shapes qpos {qpos.shape} qvel {qvel.shape}')
# MuJoCo caps <numeric> data at 500 values
if n > 500:
  sys.exit(f'{n} frames exceeds the 500-value limit of <numeric> contact data')
dt = np.diff(time)
if not np.allclose(dt, dt[0]):
  sys.exit('reference must be uniformly sampled')

airborne = np.flatnonzero(~hands & ~feet)
takeoff = time[airborne[0]] if len(airborne) else time[-1]

fmt = lambda a: ' '.join(f'{x:.6g}' for x in a)
lines = [
    '<!-- Generated by npz_to_keyframes.py from '
    f'{os.path.basename(src)}. Do not edit by hand. -->',
    '<mujoco>',
    '  <custom>',
    f'    <numeric name="launch_ref_takeoff" data="{takeoff:.6g}"/>',
    f'    <numeric name="launch_ref_hands_contact" data="{fmt(hands.astype(int))}"/>',
    f'    <numeric name="launch_ref_feet_contact" data="{fmt(feet.astype(int))}"/>',
    '  </custom>',
    '  <keyframe>',
]
for i in range(n):
  lines.append(f'    <key name="launch_ref_{i:03d}" time="{time[i]:.6g}"')
  lines.append(f'         qpos="{fmt(qpos[i])}"')
  lines.append(f'         qvel="{fmt(qvel[i])}"/>')
lines += ['  </keyframe>', '</mujoco>', '']

with open(dst, 'w', encoding='utf-8', newline='\n') as f:
  f.write('\n'.join(lines))
print(f'wrote {n} keyframes (dt={dt[0]:g}s, takeoff={takeoff:g}s) to {dst}')
